"""Tests for hooks/lib/state.py — session_id input validation (TASK-2026-00679).

Hardening against path-traversal: untrusted session_id values must be rejected
before they reach the filesystem. Defense-in-depth: even if validation is
bypassed, resolved path must remain inside STATE_DIR.

Threat model: session_id is normally generated by Claude Code as a UUID, but
the hook contract treats it as a string from JSON stdin. A malicious or
buggy upstream that injects "../../etc/passwd" must not be able to write
state files outside the configured state directory.
"""

import importlib
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "hooks"))


@pytest.fixture
def state_env(monkeypatch, tmp_path):
    """Isolate each test with its own state dir."""
    monkeypatch.setenv("CLAUDE_PLUGIN_DATA", str(tmp_path))
    from lib import state as state_mod

    importlib.reload(state_mod)
    return state_mod, tmp_path


class TestSessionIdRejection:
    """Inputs that MUST raise ValueError before any filesystem access."""

    def test_dotdot_segment_rejected(self, state_env):
        state_mod, _ = state_env
        with pytest.raises(ValueError, match="invalid session_id"):
            state_mod.SessionState("../../../etc/passwd")

    def test_forward_slash_rejected(self, state_env):
        state_mod, _ = state_env
        with pytest.raises(ValueError, match="invalid session_id"):
            state_mod.SessionState("a/b")

    def test_backslash_rejected(self, state_env):
        state_mod, _ = state_env
        with pytest.raises(ValueError, match="invalid session_id"):
            state_mod.SessionState("a\\b")

    def test_null_byte_rejected(self, state_env):
        state_mod, _ = state_env
        with pytest.raises(ValueError, match="invalid session_id"):
            state_mod.SessionState("a\x00b")

    def test_newline_rejected(self, state_env):
        state_mod, _ = state_env
        with pytest.raises(ValueError, match="invalid session_id"):
            state_mod.SessionState("a\nb")

    def test_empty_string_rejected(self, state_env):
        state_mod, _ = state_env
        with pytest.raises(ValueError, match="invalid session_id"):
            state_mod.SessionState("")

    def test_too_long_rejected(self, state_env):
        state_mod, _ = state_env
        # 65 chars > max 64
        with pytest.raises(ValueError, match="invalid session_id"):
            state_mod.SessionState("a" * 65)

    def test_special_chars_rejected(self, state_env):
        state_mod, _ = state_env
        for bad in ["a;b", "a|b", "a&b", "a$b", "a`b", "a*b", "a?b", "a:b"]:
            with pytest.raises(ValueError, match="invalid session_id"):
                state_mod.SessionState(bad)

    def test_non_string_rejected(self, state_env):
        state_mod, _ = state_env
        with pytest.raises(ValueError, match="invalid session_id"):
            state_mod.SessionState(123)  # type: ignore[arg-type]

    def test_none_rejected(self, state_env):
        state_mod, _ = state_env
        with pytest.raises(ValueError, match="invalid session_id"):
            state_mod.SessionState(None)  # type: ignore[arg-type]


class TestSessionIdAcceptance:
    """Inputs that MUST be accepted — backwards compat with existing IDs."""

    def test_uuid_like_accepted(self, state_env):
        state_mod, _ = state_env
        # Standard UUID format
        s = state_mod.SessionState("a533d28d-ce6e-4c3d-b6b2-9fac4bb7268f")
        assert s.session_id == "a533d28d-ce6e-4c3d-b6b2-9fac4bb7268f"

    def test_short_alphanumeric_accepted(self, state_env):
        state_mod, _ = state_env
        s = state_mod.SessionState("sess-1")
        assert s.session_id == "sess-1"

    def test_underscore_accepted(self, state_env):
        state_mod, _ = state_env
        s = state_mod.SessionState("test_session_42")
        assert s.session_id == "test_session_42"

    def test_existing_test_session_ids_all_pass(self, state_env):
        """All session_ids used in test_session_state.py must remain valid."""
        state_mod, _ = state_env
        # Drawn directly from tests/test_session_state.py
        existing = [
            "sess-1",
            "sess-a",
            "sess-b",
            "sess-disk",
            "defaults",
            "unknown-ns",
            "partial",
            "deep-1",
            "deep-2",
            "pc-default",
            "pc-set",
            "pc-persist",
            "init-default",
            "init-set",
            "corrupt",
            "never-existed",
            "recreate-dir",
            "tdict",
            "tdict-id",
        ]
        for sid in existing:
            s = state_mod.SessionState(sid)
            assert s.session_id == sid, f"existing id rejected: {sid!r}"

    def test_max_length_accepted(self, state_env):
        state_mod, _ = state_env
        # 64 chars exactly
        sid = "a" * 64
        s = state_mod.SessionState(sid)
        assert s.session_id == sid


class TestPathStaysInsideStateDir:
    """Defense-in-depth: even if validation regex changes, the resolved path
    must remain inside STATE_DIR. Catches symlink/race-condition edge cases.
    """

    def test_resolved_path_parent_is_state_dir(self, state_env):
        state_mod, _tmp_path = state_env
        s = state_mod.SessionState("inside-check")
        resolved = s.path.resolve()
        state_dir_resolved = state_mod.STATE_DIR.resolve()
        assert state_dir_resolved in resolved.parents, (
            f"resolved path {resolved} escapes STATE_DIR {state_dir_resolved}"
        )

    def test_no_state_file_created_on_rejected_id(self, state_env):
        state_mod, tmp_path = state_env
        with pytest.raises(ValueError):
            state_mod.SessionState("../escape-attempt")
        # No file should have been written in tmp_path or its parent
        assert list(tmp_path.glob("*.json")) == []
        assert list(tmp_path.parent.glob(".meta-state-*.json")) == []
