#!/usr/bin/env python3
"""sync-skill-registry.py — Regenerate .claude/skill-registry.json from SKILL.md.

Problem this solves: skill-registry.json was frozen at v3.1.0 bootstrap while
SKILL.md frontmatter kept evolving. Divergence crept into version, category,
token-budget, last-audit, requires, produces fields across 7+ skills. No
generator existed.

Design (hybrid per-field source of truth):
- SKILL.md wins for fields that change per-edit:
    version, last-audit, token-budget
- Registry wins for structural metadata that was carefully designed at
  v3.1.0 bootstrap and would lose fidelity if overwritten by generic
  SKILL.md frontmatter values:
    category, requires, produces, team-workers, team-consolidator
  (Fallback to SKILL.md if the registry entry is missing the field.)
- New skills that only exist in SKILL.md use SKILL.md values across the
  board (nothing to preserve yet).
- Output: valid JSON with a _generator key at top for provenance.

Usage:
  python3 scripts/sync-skill-registry.py              # Write registry.json
  python3 scripts/sync-skill-registry.py --check      # Dry-run, show diff
  python3 scripts/sync-skill-registry.py --json       # Print to stdout only
"""
import json
import os
import re
import sys
from datetime import UTC, datetime
from pathlib import Path

PLUGIN_ROOT = Path(os.environ.get(
    "CLAUDE_PLUGIN_ROOT",
    Path(__file__).parent.parent
))
SKILLS_DIR = PLUGIN_ROOT / "skills"
REGISTRY_FILE = PLUGIN_ROOT / ".claude" / "skill-registry.json"


def parse_inline_list(val: str) -> list[str]:
    """Parse YAML inline list. '[a, b, c]' -> ['a', 'b', 'c']. '[]' -> []."""
    val = val.strip()
    if not (val.startswith("[") and val.endswith("]")):
        return []
    inner = val[1:-1].strip()
    if not inner:
        return []
    return [x.strip().strip("'\"") for x in inner.split(",") if x.strip()]


def parse_frontmatter(path: Path) -> dict:
    """Parse YAML-like frontmatter from SKILL.md. Flat keys only."""
    try:
        content = path.read_text(encoding="utf-8")
    except OSError:
        return {}
    if not content.startswith("---"):
        return {}
    parts = content.split("---", 2)
    if len(parts) < 3:
        return {}
    fm = {}
    for line in parts[1].strip().split("\n"):
        line = line.rstrip()
        if not line or line.lstrip().startswith("#"):
            continue
        if ":" in line and not line.startswith((" ", "\t", "-")):
            key, _, val = line.partition(":")
            fm[key.strip()] = val.strip()
    return fm


def build_entry(skill_name: str, fm: dict, preserved: dict) -> dict:
    """Hybrid merge: SKILL.md for per-edit fields, registry for structural.

    SKILL.md wins: version, last-audit, token-budget
    Registry wins (fallback to SKILL.md if missing): category, requires,
    produces, team-workers, team-consolidator
    """
    try:
        token_budget = int(fm.get("token-budget", "0").strip("'\"")) if fm.get("token-budget") else 0
    except (ValueError, AttributeError):
        token_budget = 0

    fm_requires = parse_inline_list(fm.get("requires", "[]"))
    fm_produces = parse_inline_list(fm.get("produces", "[]"))
    fm_category = (fm.get("category") or fm.get("type") or "general").strip("'\"")

    # Registry wins for structural, but fall through if absent.
    category = preserved.get("category") or fm_category
    requires = preserved["requires"] if "requires" in preserved else fm_requires
    produces = preserved["produces"] if "produces" in preserved else fm_produces

    return {
        "version": fm.get("version", "0.0.0").strip("'\""),
        "category": category,
        "token-budget": token_budget,
        "last-audit": fm.get("last-audit", "").strip("'\""),
        "requires": requires,
        "produces": produces,
        "team-workers": preserved.get("team-workers", []),
        "team-consolidator": preserved.get("team-consolidator"),
    }


def build_registry() -> dict:
    """Scan skills/ and build full registry keyed by skill name."""
    existing = {}
    if REGISTRY_FILE.exists():
        try:
            existing = json.loads(REGISTRY_FILE.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            existing = {}

    # Preserve the _generator comment field if we collide with it
    existing.pop("_generator", None)

    registry = {
        "_generator": {
            "_comment": "auto-generated by scripts/sync-skill-registry.py — do not edit manually",
            "_source": "skills/<name>/SKILL.md frontmatter (values) + preserved team-* fields",
            "_generated_at": datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        }
    }

    if not SKILLS_DIR.exists():
        return registry

    for skill_dir in sorted(SKILLS_DIR.iterdir()):
        if not skill_dir.is_dir() or skill_dir.name.startswith((".", "_")):
            continue
        skill_md = skill_dir / "SKILL.md"
        if not skill_md.exists():
            continue
        skill_name = skill_dir.name
        fm = parse_frontmatter(skill_md)
        preserved = existing.get(skill_name, {})
        registry[skill_name] = build_entry(skill_name, fm, preserved)

    return registry


def compute_diff(new_registry: dict) -> list[str]:
    """Compare new registry vs on-disk. Return list of change descriptions."""
    if not REGISTRY_FILE.exists():
        return ["registry.json does not exist yet — would create fresh"]
    try:
        old = json.loads(REGISTRY_FILE.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as e:
        return [f"registry.json exists but could not parse: {e}"]

    diffs = []
    skills_to_compare = {k for k in new_registry if not k.startswith("_")}
    for skill in sorted(skills_to_compare):
        old_entry = old.get(skill, {})
        new_entry = new_registry[skill]
        for field in ("version", "category", "token-budget", "last-audit",
                      "requires", "produces"):
            if old_entry.get(field) != new_entry.get(field):
                diffs.append(
                    f"  {skill}.{field}: {old_entry.get(field)!r} -> {new_entry.get(field)!r}"
                )

    added = skills_to_compare - set(old.keys())
    removed = set(old.keys()) - skills_to_compare - {"_generator"}
    for skill in sorted(added):
        diffs.append(f"  + {skill}: added (SKILL.md exists but not in registry)")
    for skill in sorted(removed):
        diffs.append(f"  - {skill}: removed (in registry but no SKILL.md)")

    return diffs


def main():
    check_only = "--check" in sys.argv
    as_json = "--json" in sys.argv

    registry = build_registry()

    if as_json:
        print(json.dumps(registry, indent=2, ensure_ascii=False))
        return 0

    diffs = compute_diff(registry)

    if check_only:
        if not diffs:
            print("No changes. registry.json is in sync with SKILL.md.")
            return 0
        print(f"Would change {len(diffs)} field(s) in {REGISTRY_FILE}:")
        for d in diffs:
            print(d)
        return 0

    REGISTRY_FILE.parent.mkdir(parents=True, exist_ok=True)
    REGISTRY_FILE.write_text(
        json.dumps(registry, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    skill_count = sum(1 for k in registry if not k.startswith("_"))
    print(f"Wrote {REGISTRY_FILE} ({skill_count} skills, {len(diffs)} field updates)")
    if diffs:
        print("\nChanges:")
        for d in diffs:
            print(d)
    return 0


if __name__ == "__main__":
    sys.exit(main())
